[package]
name = "diatonic"
version = "0.1.0"
edition = "2021"
authors = ["Mike AntonovMA@outlook.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "harmony"
path = "bin/harmony.rs"